from enum import Enum


class AssetType(str, Enum):
    STOCK = "STOCK"
    ETF = "ETF"


class Direction(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"
    PAIR_LONG_SHORT = "PAIR_LONG_SHORT"
    PAIR_SHORT_LONG = "PAIR_SHORT_LONG"


class MarketRegime(str, Enum):
    TREND_UP = "TREND_UP"
    TREND_DOWN = "TREND_DOWN"
    RANGE = "RANGE"
    BREAKOUT_EXPANSION = "BREAKOUT_EXPANSION"
    MEAN_REVERTING = "MEAN_REVERTING"
    HIGH_VOL_UNSTABLE = "HIGH_VOL_UNSTABLE"
    NO_TRADE = "NO_TRADE"


class StrategyName(str, Enum):
    VWAP_TREND_CONTINUATION = "VWAP_TREND_CONTINUATION"
    OPENING_RANGE_BREAKOUT = "OPENING_RANGE_BREAKOUT"
    RELATIVE_STRENGTH_LEADER = "RELATIVE_STRENGTH_LEADER"
    BREAKOUT_UNUSUAL_VOLUME = "BREAKOUT_UNUSUAL_VOLUME"
    PULLBACK_TO_VWAP = "PULLBACK_TO_VWAP"
    MEAN_REVERSION_EXTENSION = "MEAN_REVERSION_EXTENSION"
    GAP_CONTINUATION_FADE = "GAP_CONTINUATION_FADE"
    ETF_PAIRS_RELATIVE_VALUE = "ETF_PAIRS_RELATIVE_VALUE"


class SignalGrade(str, Enum):
    A = "A"
    B = "B"
    C = "C"
    SUPPRESSED = "SUPPRESSED"


class RecommendationStatus(str, Enum):
    ACTIVE = "ACTIVE"
    REJECTED = "REJECTED"
    INVALIDATED = "INVALIDATED"
    EXPIRED = "EXPIRED"
