/**
 * Morning Briefing Worker
 * Runs at 9:00 AM ET each trading day
 * Generates and stores daily market brief
 */

import { fetchMarketSnapshot, getMockMarketData } from '../server/market-data';
import { analyzeNews, getMockNewsAnalysis } from '../server/news-analyzer';
import { generateMorningBrief } from '../server/ai-briefing';
import { runStrategyEngine, assessRiskLevel, MarketConditions } from '../lib/models/strategy-engine';
import { classifyVIXRegime } from '../lib/models/volatility';
import { db } from '../database/db';
import { morningBriefings } from '../database/schema';
import { dispatchAlert, formatMorningBriefAlert } from './alert-system';

async function runMorningBriefing() {
  console.log('=== SPX Signal Desk — Morning Briefing Worker ===');
  console.log(`Time: ${new Date().toISOString()}`);
  console.log('');

  try {
    // Fetch market data
    console.log('Fetching market data...');
    const snapshot = process.env.MARKETDATA_API_KEY
      ? await fetchMarketSnapshot()
      : getMockMarketData();
    console.log(`SPX: ${snapshot.spx.price.toFixed(2)}, VIX: ${snapshot.vix.price.toFixed(2)}`);

    // Analyze news
    console.log('Analyzing news...');
    const newsAnalysis = process.env.GNEWS_API_KEY
      ? await analyzeNews()
      : getMockNewsAnalysis();
    console.log(`News sentiment: ${newsAnalysis.overallSentiment}, Tradeability: ${newsAnalysis.tradeabilityScore}`);

    // Build market conditions
    const { spx, vix } = snapshot;
    const impliedVol = vix.price / 100;
    const ivRankValue = Math.min(100, Math.max(0, (vix.price - 12) / (40 - 12) * 100));

    const conditions: MarketConditions = {
      spxPrice: spx.price,
      spyPrice: snapshot.spy.price,
      vix: vix.price,
      vixRegime: classifyVIXRegime(vix.price),
      vixPctile: ivRankValue,
      ivRank: ivRankValue,
      directionalBias: newsAnalysis.overallSentiment === 'bullish' ? 'bullish' : newsAnalysis.overallSentiment === 'bearish' ? 'bearish' : 'neutral',
      marketRegime: Math.abs(spx.changePct) > 1.5 ? 'volatile' : spx.changePct > 0.5 ? 'trending_up' : spx.changePct < -0.5 ? 'trending_down' : 'range_bound',
      riskLevel: 'moderate',
      isMacroEventDay: newsAnalysis.macroRiskLevel === 'high',
      isExpiry: false,
      timeOfDay: 900,
      spxDailyChange: spx.changePct || 0,
      technicalSignal: 'neutral',
      realizedVol: impliedVol * 0.85,
      impliedVol,
      skew: null,
    };

    conditions.riskLevel = assessRiskLevel(conditions);

    // Run strategy engine
    console.log('Running strategy engine...');
    const decision = runStrategyEngine(conditions);
    console.log(`Strategy: ${decision.strategy}`);

    if (decision.recommendation && decision.recommendation.tradeType !== 'no_trade') {
      const rec = decision.recommendation;
      console.log(`Trade: ${rec.tradeType} | ${rec.shortLeg?.strike}/${rec.longLeg?.strike}`);
      console.log(`Credit: $${rec.credit?.toFixed(2)} | POP: ${(rec.probOfProfit * 100).toFixed(1)}%`);
      console.log(`EV: $${rec.expectedValue?.toFixed(2)} | Confidence: ${rec.confidence}`);
    } else {
      console.log('No trade today.');
    }

    // Generate briefing
    console.log('Generating AI briefing...');
    const brief = await generateMorningBrief(snapshot, newsAnalysis, decision);

    console.log('\n=== MORNING BRIEF ===');
    console.log(brief.executiveSummary);
    console.log('\nStrategy:', brief.strategyOutlook);
    console.log('Generated by:', brief.generatedBy);

    // Save to database
    const today = new Date().toISOString().split('T')[0];
    try {
      await db.insert(morningBriefings).values({
        date: today,
        marketSummary: brief.marketOverview,
        geopoliticalRisk: brief.geopoliticalRisk,
        macroAnalysis: brief.volatilityAnalysis,
        strategyRecommendation: brief.strategyOutlook,
        riskLevel: conditions.riskLevel,
        shouldTrade: decision.recommendation?.tradeType !== 'no_trade',
        newsHighlights: newsAnalysis.items.slice(0, 5).map(n => ({ headline: n.headline, sentiment: n.sentiment })),
        fullBrief: brief.fullText,
      }).onConflictDoUpdate({
        target: morningBriefings.date,
        set: {
          marketSummary: brief.marketOverview,
          strategyRecommendation: brief.strategyOutlook,
          riskLevel: conditions.riskLevel,
          fullBrief: brief.fullText,
        },
      });
      console.log(`✓ Briefing saved to database for ${today}`);
    } catch (dbErr) {
      console.error('Failed to save briefing to database:', dbErr);
    }

    // Send morning brief notification
    const alertPhone = process.env.ALERT_PHONE;
    const alertEmail = process.env.ALERT_EMAIL;

    if (alertPhone || alertEmail) {
      const message = formatMorningBriefAlert(
        spx.price,
        vix.price,
        decision.strategy,
        conditions.riskLevel,
        brief.executiveSummary
      );

      if (alertPhone) {
        await dispatchAlert({
          type: 'morning_brief',
          title: `SPX Signal Desk — ${today}`,
          message,
          priority: 'normal',
          channel: 'sms',
          phone: alertPhone,
        });
      }

      if (alertEmail) {
        await dispatchAlert({
          type: 'morning_brief',
          title: `SPX Signal Desk Morning Brief — ${today}`,
          message,
          priority: 'normal',
          channel: 'email',
          email: alertEmail,
        });
      }
    }

    console.log('\n✓ Morning briefing complete');
    return { brief, decision, conditions };

  } catch (err) {
    console.error('Morning briefing failed:', err);
    process.exit(1);
  }
}

// Run if called directly
runMorningBriefing().then(() => {
  process.exit(0);
}).catch(err => {
  console.error(err);
  process.exit(1);
});
